/*
 * loadMap.java
 *
 * Created on February 15, 2009, 5:32 PM
 */

package botmania;
import java.awt.*;
import java.io.FilenameFilter;
import java.io.File;
import java.io.IOException;
import java.lang.Object.*;
import java.util.logging.Level;
import java.util.logging.Logger;
    
/**
 *
 * @author  avijit
 */


public class loadMap extends javax.swing.JFrame {

    /** Creates new form loadMap */
    public loadMap() {
        initComponents();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setIconImage(Toolkit.getDefaultToolkit().getImage("ico.jpg"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Select The Map you want to match in");

        jTextField1.setEnabled(false);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Compile All Codes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.setEnabled(false);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField3.setEnabled(false);
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField4.setEnabled(false);
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton5.setText("Browse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Team1 codes");

        jTextField5.setEnabled(false);
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton6.setText("Browse");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField6.setEnabled(false);
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton7.setText("Browse");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField7.setEnabled(false);
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jButton8.setText("Browse");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Team 2 codes");

        jLabel4.setText("bot 1");

        jLabel5.setText("bot 2");

        jLabel6.setText("bot 3");

        jLabel7.setText("bot 5");

        jLabel8.setText("bot 6");

        jLabel9.setText("bot 4");

        jButton9.setText("Run Game Server!");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel10.setText("Locate g++.exe file (in dev-cpp\\bin) ");

        jTextField8.setText("c:\\Dev-Cpp\\bin\\g++.exe");
        jTextField8.setEnabled(false);
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jButton10.setText("Browse");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel11.setText("Compile and Execute Code");

        jButton11.setText("Compile bot1");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Compile bot2");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Compile bot3");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Compile bot4");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Compile bot5");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Compile bot6");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel1))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField8)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton3)
                                            .addComponent(jButton5)
                                            .addComponent(jButton4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8))
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton6)
                                            .addComponent(jButton7)
                                            .addComponent(jButton8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(jLabel3))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jLabel8)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jButton5)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jButton4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jButton16)
                    .addComponent(jButton15)
                    .addComponent(jButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_jTextField2ActionPerformed

private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField3ActionPerformed

private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField4ActionPerformed

private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField5ActionPerformed

private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField6ActionPerformed

private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField7ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    try{
    Frame f=new Frame();
    FileDialog fd=new FileDialog(f);
    fd.setMode(FileDialog.LOAD);
    fd.setVisible(true);
    
    
    if(fd.getFile().endsWith(".bMap")!=true)
    {
       errorPage obj=new errorPage("The extension to this file is not correct.\nPlease select the correct file with extension .bMap");
       obj.setVisible(true);
       Integer.parseInt("a");      

    }
    if(fd.getDirectory()!=null && fd.getFile()!=null)
    jTextField1.setText(fd.getDirectory()+fd.getFile());
    }
    catch (Exception e)
    {
        
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
// TODO add your handling code here:
    if(jTextField1.getText().equals("")==false)
    {
        startGame ob=new startGame(jTextField1.getText());
        ob.initAll();
    }
    else 
    {   
        startGame ob=new startGame();
        ob.initAll();
    }
    
    
}//GEN-LAST:event_jButton9ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
try{
    //-DLINUX -o bot1 "+jTextField2.getText()+" -lwsock32 -lm" jTextField8.getText()+  -DLINUX -o bot3 C:\\Documents and Settings\\avijit\\Desktop\\crap\\botMania_alpha\\botMania_alpha\\botMania_for_windows\\bot3.cpp -lwsock32 -lm"
   //System.out.print(c(jTextField2.getText()));
  // Process child2 = Runtime.getRuntime().exec("c:\\Dev-Cpp\\bin\\g++.exe -DLINUX -o bot1 \"C:\\Documents and Settings\\avijit\\Desktop\\crap\\botMania_alpha\\botMania_alpha\\botMania_for_windows\\bot1.cpp\" -lwsock32 -lm");
//System.out.print("c:\\Dev-Cpp\\bin\\g++.exe -DLINUX -o bot1 \"C:\\Documents and Settings\\avijit\\Desktop\\crap\\botMania_alpha\\botMania_alpha\\botMania_for_windows\\bot1.cpp -lwsock32 -lm\"");

if(jTextField8.getText().trim().equals("")){errorPage o=new errorPage("The g++ compiler for dev-cpp is unspecified!");o.setVisible(true);Integer.parseInt("a");}

if(jTextField2.getText().trim().equals("")){errorPage o=new errorPage("The bot1 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}
if(jTextField4.getText().trim().equals("")){errorPage o=new errorPage("The bot2 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}
if(jTextField3.getText().trim().equals("")){errorPage o=new errorPage("The bot3 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}
if(jTextField5.getText().trim().equals("")){errorPage o=new errorPage("The bot4 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}
if(jTextField7.getText().trim().equals("")){errorPage o=new errorPage("The bot5 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}
if(jTextField6.getText().trim().equals("")){errorPage o=new errorPage("The bot6 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}


 Process child1 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+" -DLINUX -o bot1 "+"\""+c(jTextField2.getText())+"\" -lwsock32 -lm");

Process child2 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+" -DLINUX -o bot2 "+"\""+c(jTextField4.getText())+"\" -lwsock32 -lm");

Process child3 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+ "-DLINUX -o bot3 "+"\""+c(jTextField3.getText())+"\" -lwsock32 -lm");

Process child4 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+ "-DLINUX -o bot4 "+"\""+c(jTextField5.getText())+"\" -lwsock32 -lm");

Process child5 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+ "-DLINUX -o bot5 "+"\""+c(jTextField7.getText())+"\" -lwsock32 -lm");

Process child6 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+ "-DLINUX -o bot6 "+"\""+c(jTextField6.getText())+"\" -lwsock32 -lm");
Thread.sleep(50);

jButton11.setText("Compiled!");
jButton12.setText("Compiled!");
jButton13.setText("Compiled!");
jButton14.setText("Compiled!");
jButton15.setText("Compiled!");
jButton16.setText("Compiled!");

 jButton9.setEnabled(true);

// Process child4 = Runtime.getRuntime().exec(jTextField8.getText()+" -DLINUX -o bot4 "+jTextField5.getText()+" -lwsock32 -lm");

  //  Process child5 = Runtime.getRuntime().exec(jTextField8.getText()+" -DLINUX -o bot5 "+jTextField7.getText()+" -lwsock32 -lm");

   // Process child6 = Runtime.getRuntime().exec(jTextField8.getText()+" -DLINUX -o bot6 "+jTextField6.getText()+" -lwsock32 -lm");

}
catch(Exception e){System.out.print(e);}
    
    
   
}//GEN-LAST:event_jButton2ActionPerformed

private String c(String a)
{
    //System.out.print("here");
String res="";
for(int i=0;i<a.length();i++)
  
{   
    //System.out.print("here");
    if(a.charAt(i)!='\\')
    {//System.out.print("here");
    res=res+a.charAt(i);}
    else res=res+"\\\\";
}
//System.out.print(res);
return res;
}


private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    Frame f=new Frame();
    FileDialog fd=new FileDialog(f);
    fd.setMode(FileDialog.LOAD);
   
    fd.setVisible(true);
     if(fd.getDirectory()!=null && fd.getFile()!=null)
     jTextField2.setText(fd.getDirectory()+fd.getFile());
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    Frame f=new Frame();
    FileDialog fd=new FileDialog(f);
    fd.setMode(FileDialog.LOAD);
   
    fd.setVisible(true);
     if(fd.getDirectory()!=null && fd.getFile()!=null)
     jTextField4.setText(fd.getDirectory()+fd.getFile());
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    Frame f=new Frame();
    FileDialog fd=new FileDialog(f);
    fd.setMode(FileDialog.LOAD);
   
    fd.setVisible(true);
     if(fd.getDirectory()!=null && fd.getFile()!=null)
     jTextField3.setText(fd.getDirectory()+fd.getFile());
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
    Frame f=new Frame();
    FileDialog fd=new FileDialog(f);
    fd.setMode(FileDialog.LOAD);
   
    fd.setVisible(true);
     if(fd.getDirectory()!=null && fd.getFile()!=null)
     jTextField5.setText(fd.getDirectory()+fd.getFile());
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
    Frame f=new Frame();
    FileDialog fd=new FileDialog(f);
    fd.setMode(FileDialog.LOAD);
   
    fd.setVisible(true);
     if(fd.getDirectory()!=null && fd.getFile()!=null)
     jTextField7.setText(fd.getDirectory()+fd.getFile());
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    Frame f=new Frame();
    FileDialog fd=new FileDialog(f);
    fd.setMode(FileDialog.LOAD);
   
    fd.setVisible(true);
     if(fd.getDirectory()!=null && fd.getFile()!=null)
     jTextField6.setText(fd.getDirectory()+fd.getFile());
}//GEN-LAST:event_jButton7ActionPerformed

private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
// TODO add your handling code here:
    java.awt.event.ActionEvent ev=null;
   jButton1ActionPerformed(ev);
}//GEN-LAST:event_jTextField1MouseClicked

private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
// TODO add your handling code here:
     java.awt.event.ActionEvent ev=null;
   jButton5ActionPerformed(ev);
}//GEN-LAST:event_jTextField4MouseClicked

private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
// TODO add your handling code here:
    java.awt.event.ActionEvent ev=null;
   jButton3ActionPerformed(ev);
     
}//GEN-LAST:event_jTextField2MouseClicked

private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
// TODO add your handling code here:
   java.awt.event.ActionEvent ev=null;
   jButton4ActionPerformed(ev);
}//GEN-LAST:event_jTextField3MouseClicked

private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
// TODO add your handling code here:
     java.awt.event.ActionEvent ev=null;
   jButton6ActionPerformed(ev);
}//GEN-LAST:event_jTextField5MouseClicked

private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
// TODO add your handling code here:
     java.awt.event.ActionEvent ev=null;
   jButton8ActionPerformed(ev);
}//GEN-LAST:event_jTextField7MouseClicked

private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
// TODO add your handling code here:
     java.awt.event.ActionEvent ev=null;
   jButton7ActionPerformed(ev);
}//GEN-LAST:event_jTextField6MouseClicked

private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
// TODO add your handling code here:
     java.awt.event.ActionEvent ev=null;
   jButton10ActionPerformed(ev);
}//GEN-LAST:event_jTextField8MouseClicked

private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField8ActionPerformed

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
// TODO add your handling code here:
    
     try{
    Frame f=new Frame();
    FileDialog fd=new FileDialog(f);
    fd.setMode(FileDialog.LOAD);
    fd.setVisible(true);
    
    
    if(fd.getFile().equals(("g++.exe"))!=true)
    {
       errorPage obj=new errorPage("The extension to this file is not correct.\nPlease select the correct file with extension .bMap");
       obj.setVisible(true);
       Integer.parseInt("a");      

    }
    if(fd.getDirectory()!=null && fd.getFile()!=null)
    jTextField8.setText(fd.getDirectory()+fd.getFile());
    }
    catch (Exception e)
    {
        
    }
}//GEN-LAST:event_jButton10ActionPerformed

private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
// TODO add your handling code here:
            if(jTextField8.getText().trim().equals("")){errorPage o=new errorPage("The g++ compiler for dev-cpp is unspecified!");o.setVisible(true);Integer.parseInt("a");}
            
            if(jTextField4.getText().trim().equals("")){errorPage o=new errorPage("The bot2 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}

            Process child2 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+" -DLINUX -o bot2 "+"\""+c(jTextField4.getText())+"\" -lwsock32 -lm");
            Thread.sleep(20);
            jButton9.setEnabled(true);
 jButton12.setText("Compiled!");
}       catch (InterruptedException ex) {
            Logger.getLogger(loadMap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            
        }

   
}//GEN-LAST:event_jButton12ActionPerformed

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
// TODO add your handling code here:
            if(jTextField8.getText().trim().equals("")){errorPage o=new errorPage("The g++ compiler for dev-cpp is unspecified!");o.setVisible(true);Integer.parseInt("a");}
            if(jTextField2.getText().trim().equals("")){errorPage o=new errorPage("The bot1 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}

            
             Process child1 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+" -DLINUX -o bot1 "+"\""+c(jTextField2.getText())+"\" -lwsock32 -lm");
             
             Thread.sleep(20);

             jButton9.setEnabled(true);
             jButton11.setText("Compiled!");
        } catch (InterruptedException ex) {
            Logger.getLogger(loadMap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
           
        }

}//GEN-LAST:event_jButton11ActionPerformed

private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
// TODO add your handling code here:
           if(jTextField8.getText().trim().equals("")){errorPage o=new errorPage("The g++ compiler for dev-cpp is unspecified!");o.setVisible(true);Integer.parseInt("a");}
            
            if(jTextField3.getText().trim().equals("")){errorPage o=new errorPage("The bot3 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}

            Process child3 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+ "-DLINUX -o bot3 "+"\""+c(jTextField3.getText())+"\" -lwsock32 -lm");
             Thread.sleep(20); 
            jButton9.setEnabled(true);
             jButton13.setText("Compiled!");
        } catch (InterruptedException ex) {
            Logger.getLogger(loadMap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
           
        }

    
}//GEN-LAST:event_jButton13ActionPerformed

private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
// TODO add your handling code here:
if(jTextField8.getText().trim().equals("")){errorPage o=new errorPage("The g++ compiler for dev-cpp is unspecified!");o.setVisible(true);Integer.parseInt("a");}
            
            if(jTextField5.getText().trim().equals("")){errorPage o=new errorPage("The bot4 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}

Process child4 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+ "-DLINUX -o bot4 "+"\""+c(jTextField5.getText())+"\" -lwsock32 -lm");
 Thread.sleep(20); 
jButton9.setEnabled(true);
 jButton14.setText("Compiled!");
        } catch (InterruptedException ex) {
            Logger.getLogger(loadMap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
          
        }

    
}//GEN-LAST:event_jButton14ActionPerformed

private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try {
// TODO add your handling code here:
            if(jTextField8.getText().trim().equals("")){errorPage o=new errorPage("The g++ compiler for dev-cpp is unspecified!");o.setVisible(true);Integer.parseInt("a");}
            
            if(jTextField7.getText().trim().equals("")){errorPage o=new errorPage("The bot5 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}

Process child5 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+ "-DLINUX -o bot5 "+"\""+c(jTextField7.getText())+"\" -lwsock32 -lm");
 Thread.sleep(20); 
jButton9.setEnabled(true);
 jButton15.setText("Compiled!");
        } catch (InterruptedException ex) {
            Logger.getLogger(loadMap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            
        }

    
}//GEN-LAST:event_jButton15ActionPerformed

private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
// TODO add your handling code here:
           if(jTextField8.getText().trim().equals("")){errorPage o=new errorPage("The g++ compiler for dev-cpp is unspecified!");o.setVisible(true);Integer.parseInt("a");}
            
            if(jTextField6.getText().trim().equals("")){errorPage o=new errorPage("The bot6 file is unspecified!");o.setVisible(true);Integer.parseInt("a");}

            Process child6 = Runtime.getRuntime().exec("\""+c(jTextField8.getText())+"\""+ "-DLINUX -o bot6 "+"\""+c(jTextField6.getText())+"\" -lwsock32 -lm");
             Thread.sleep(20);
            jButton9.setEnabled(true);
             jButton16.setText("Compiled!");
        } catch (InterruptedException ex) {
            Logger.getLogger(loadMap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            
        }

}//GEN-LAST:event_jButton16ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loadMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
